<a href="https://colab.research.google.com/github/aannddrree/disciplinaIA/blob/main/aula_etica_impactos_ia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Unidade 5 — Ética e Impactos da Inteligência Artificial

## Aula prática com Python

**Tema:** Ética no desenvolvimento e uso de IA, viés nos dados e algoritmos, e impactos da IA no mercado de trabalho.

**Objetivo da aula:** demonstrar, na prática, que um modelo de IA pode tomar decisões injustas quando os dados usados no treinamento possuem viés.

---

## Contexto

A Inteligência Artificial não é neutra. Ela aprende padrões a partir dos dados usados no treinamento.

Se os dados históricos possuem preconceitos, desigualdades ou decisões injustas, o modelo pode aprender esses padrões e reproduzi-los.

Nesta aula, vamos simular uma IA usada para selecionar candidatos para uma entrevista de emprego.

## Situação-problema

Imagine que uma empresa quer usar IA para selecionar candidatos.

O sistema será treinado com dados antigos da própria empresa.

O problema é que, no passado, a empresa pode ter contratado menos pessoas de determinado grupo social. Assim, o modelo pode aprender esse comportamento injusto.

Nesta atividade, usaremos um campo chamado `grupo`, que representa um atributo sensível fictício.

- `grupo = 0`: Grupo A
- `grupo = 1`: Grupo B
- `contratado = 0`: Não contratado
- `contratado = 1`: Contratado

In [1]:
# Importando as bibliotecas necessárias
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

print("Bibliotecas importadas com sucesso!")

Bibliotecas importadas com sucesso!

## Criando uma base de dados fictícia

A base abaixo representa candidatos avaliados por uma empresa.

Cada candidato possui:

- anos de experiência;
- nota em um teste técnico;
- grupo social fictício;
- decisão histórica de contratação.

Atenção: os dados são fictícios e foram criados apenas para fins didáticos.

In [2]:
dados = pd.DataFrame({
    'experiencia': [1,2,3,4,5,6,7,8,2,3,4,5,6,7,8,9],
    'nota_teste': [60,65,70,75,80,85,90,95,62,67,72,77,82,87,92,97],
    'grupo': [0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1],
    'contratado': [0,0,0,1,1,1,1,1,0,0,0,0,1,1,1,1]
})

dados

    experiencia  nota_teste  grupo  contratado
0             1          60      0           0
1             2          65      0           0
2             3          70      0           0
3             4          75      0           1
4             5          80      0           1
5             6          85      0           1
6             7          90      0           1
7             8          95      0           1
8             2          62      1           0
9             3          67      1           0
10            4          72      1           0
11            5          77      1           0
12            6          82      1           1
13            7          87      1           1
14            8          92      1           1
15            9          97      1           1

## O que é `DecisionTreeClassifier`?

`DecisionTreeClassifier` é um algoritmo de Machine Learning usado para problemas de classificação.

Ele funciona como uma árvore de decisão, parecida com um fluxograma.

Exemplo:

```text
A nota foi maior que 70?
 ├── SIM → Contratar
 └── NÃO → Não contratar
```

Depois ele pode criar outras perguntas:

```text
Tem mais de 3 anos de experiência?
 ├── SIM → Contratar
 └── NÃO → Não contratar
```

Esse algoritmo é interessante para esta aula porque é simples, visual e ajuda a entender como uma IA pode tomar decisões com base nos dados.

## Separando entradas e saída

Em Machine Learning, normalmente separamos os dados em:

- `X`: dados de entrada, ou seja, as informações usadas para tomar a decisão;
- `y`: resposta esperada, ou seja, aquilo que o modelo deve aprender a prever.

Neste exemplo:

- `X`: experiência, nota no teste e grupo;
- `y`: se o candidato foi contratado ou não.

In [3]:
X = dados[['experiencia', 'nota_teste', 'grupo']]
y = dados['contratado']

print("Dados de entrada:")
display(X.head())

print("Resposta esperada:")
display(y.head())

Dados de entrada:

   experiencia  nota_teste  grupo
0            1          60      0
1            2          65      0
2            3          70      0
3            4          75      0
4            5          80      0

Resposta esperada:

0    0
1    0
2    0
3    1
4    1
Name: contratado, dtype: int64

## Dividindo dados de treino e teste

Vamos dividir a base em duas partes:

- dados de treino: usados para ensinar o modelo;
- dados de teste: usados para avaliar o modelo.

O parâmetro `random_state=42` serve para que o resultado seja reproduzível, ou seja, para que a divisão dos dados seja sempre a mesma quando o código for executado novamente.

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

print("Quantidade de dados para treino:", len(X_train))
print("Quantidade de dados para teste:", len(X_test))

Quantidade de dados para treino: 11
Quantidade de dados para teste: 5

## Treinando o modelo

Agora vamos criar uma árvore de decisão e treinar o modelo com os dados históricos.

O comando `fit()` é responsável por treinar a IA.

```python
modelo.fit(X_train, y_train)
```

Isso significa que o modelo vai procurar padrões entre os dados de entrada e a resposta esperada.

In [5]:
modelo = DecisionTreeClassifier(random_state=42)
modelo.fit(X_train, y_train)

print("Modelo treinado com sucesso!")

Modelo treinado com sucesso!

## Avaliando o modelo

Agora vamos usar os dados de teste para verificar se o modelo conseguiu aprender algum padrão.

A acurácia mostra a proporção de acertos do modelo.

A matriz de confusão ajuda a comparar os valores reais com as previsões.

| Tipo | Valor | Explicação                  |
| ---- | ----- | --------------------------- |
| TN   | 2     | acertou 2 “não contratados” |
| FP   | 0     | não errou nenhum falso SIM  |
| FN   | 0     | não errou nenhum falso NÃO  |
| TP   | 3     | acertou 3 “contratados”     |

In [6]:
previsoes = modelo.predict(X_test)

print("Acurácia:", accuracy_score(y_test, previsoes))
print("Matriz de confusão:")
print(confusion_matrix(y_test, previsoes))

Acurácia: 1.0
Matriz de confusão:
[[2 0]
 [0 3]]

## Testando novos candidatos

Agora vamos criar dois candidatos com as mesmas características:

- mesma experiência;
- mesma nota no teste;
- grupos diferentes.

A ideia é observar se o modelo muda a decisão apenas por causa do grupo.

In [10]:
novos_candidatos = pd.DataFrame({
    'experiencia': [4, 4],
    'nota_teste': [75, 75],
    'grupo': [0, 1]
})

resultado = modelo.predict(novos_candidatos)

novos_candidatos['resultado_IA'] = resultado
novos_candidatos['resultado_texto'] = novos_candidatos['resultado_IA'].map({0: 'Não contratar', 1: 'Contratar'})

novos_candidatos

   experiencia  nota_teste  grupo  resultado_IA resultado_texto
0            4          75      0             1       Contratar
1            4          75      1             0   Não contratar

## Discussão ética

Observe o resultado anterior.

Os dois candidatos possuem a mesma experiência e a mesma nota no teste.

A pergunta principal é:

> A IA tomou a mesma decisão para os dois candidatos?

Se a decisão for diferente apenas por causa do campo `grupo`, temos um exemplo de viés algorítmico.

Isso mostra que uma IA pode reproduzir decisões injustas presentes nos dados históricos.

## Versão alternativa: removendo o atributo sensível

Uma tentativa de reduzir o viés é remover o atributo sensível da base.

Neste caso, vamos treinar o modelo sem usar o campo `grupo`.

Atenção: remover o atributo sensível ajuda, mas nem sempre resolve completamente o problema.

Outros campos, como bairro, escola, renda ou histórico profissional, podem funcionar como indicadores indiretos de desigualdade.

In [11]:
X_sem_grupo = dados[['experiencia', 'nota_teste']]
y = dados['contratado']

X_train, X_test, y_train, y_test = train_test_split(
    X_sem_grupo, y, test_size=0.3, random_state=42
)

modelo_sem_grupo = DecisionTreeClassifier(random_state=42)
modelo_sem_grupo.fit(X_train, y_train)

print("Modelo sem o atributo grupo treinado com sucesso!")

Modelo sem o atributo grupo treinado com sucesso!

In [12]:
novos_candidatos_sem_grupo = pd.DataFrame({
    'experiencia': [4, 4],
    'nota_teste': [75, 75]
})

resultado_sem_grupo = modelo_sem_grupo.predict(novos_candidatos_sem_grupo)

novos_candidatos_sem_grupo['resultado_IA'] = resultado_sem_grupo
novos_candidatos_sem_grupo['resultado_texto'] = novos_candidatos_sem_grupo['resultado_IA'].map({0: 'Não contratar', 1: 'Contratar'})

novos_candidatos_sem_grupo

   experiencia  nota_teste  resultado_IA resultado_texto
0            4          75             1       Contratar
1            4          75             1       Contratar

## Comparação dos resultados

Agora compare:

1. O modelo usando o campo `grupo`.
2. O modelo sem usar o campo `grupo`.

Questões para reflexão:

- O resultado mudou?
- O modelo ficou mais justo?
- Basta remover o atributo sensível?
- Como uma empresa deveria validar esse tipo de sistema antes de colocá-lo em produção?

## Discussão sobre IA e mercado de trabalho

A IA pode trazer impactos positivos e negativos para o mercado de trabalho.

### Possíveis impactos positivos

- Automação de tarefas repetitivas.
- Aumento de produtividade.
- Apoio à tomada de decisão.
- Criação de novas profissões.
- Melhoria em processos de análise de dados.

### Possíveis impactos negativos

- Substituição de algumas funções operacionais.
- Dependência excessiva de sistemas automatizados.
- Decisões injustas quando os modelos são mal treinados.
- Falta de transparência sobre como a IA decide.
- Redução de oportunidades para grupos já vulneráveis.

### Novas profissões relacionadas à IA

- Engenheiro de Machine Learning.
- Engenheiro de Dados.
- Analista de Ética em IA.
- Especialista em Governança de IA.
- Auditor de Algoritmos.
- Engenheiro de Prompt.
- Especialista em Segurança de IA.

## Atividade para os alunos

Em grupos, os alunos devem responder:

1. Onde apareceu o viés no exemplo?
2. Por que esse viés é um problema ético?
3. Quem seria responsável se essa IA prejudicasse um candidato?
4. Que medidas poderiam ser adotadas para reduzir o viés?
5. Como a IA pode impactar o mercado de trabalho nos próximos anos?

---

## Entrega sugerida

Cada grupo deverá entregar:

1. O notebook executado.
2. Um pequeno relatório com as respostas da atividade.
3. Uma conclusão sobre o uso ético da IA em processos seletivos.

## Conclusão

A principal mensagem desta aula é:

> A IA não é neutra. Ela aprende padrões a partir dos dados. Se os dados carregam injustiças, a IA pode repetir ou ampliar essas injustiças.

Por isso, desenvolver IA exige responsabilidade, análise crítica, transparência e preocupação com os impactos sociais.